# Generated by Django 6.0.2 on 2026-02-07 08:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyUsageSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('total_requests', models.PositiveIntegerField(default=0)),
                ('total_input_tokens', models.PositiveIntegerField(default=0)),
                ('total_output_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('total_cost_usd', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('model_breakdown', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'daily_usage_summary',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='HourlyPerformanceSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hour', models.DateTimeField(db_index=True)),
                ('endpoint', models.CharField(blank=True, max_length=200, null=True)),
                ('total_requests', models.PositiveIntegerField(default=0)),
                ('avg_response_time_ms', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('p50_response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('p95_response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('p99_response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('error_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
            ],
            options={
                'db_table': 'hourly_performance_summary',
                'ordering': ['-hour'],
            },
        ),
        migrations.CreateModel(
            name='RequestMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('endpoint', models.CharField(db_index=True, max_length=200)),
                ('method', models.CharField(max_length=10)),
                ('response_time_ms', models.PositiveIntegerField()),
                ('llm_latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('db_latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('status_code', models.PositiveIntegerField()),
                ('is_error', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('time_to_first_token_ms', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'request_metrics',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SystemHealth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('service_name', models.CharField(choices=[('api', 'API Server'), ('database', 'Database'), ('llm_groq', 'Groq LLM'), ('llm_gemini', 'Gemini LLM'), ('pinecone', 'Pinecone Vector DB')], db_index=True, max_length=100)),
                ('is_healthy', models.BooleanField(default=True)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'system_health',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TokenUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('model_name', models.CharField(max_length=100)),
                ('provider', models.CharField(max_length=50)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('request_type', models.CharField(choices=[('chat', 'Chat'), ('embedding', 'Embedding'), ('rag_query', 'RAG Query')], default='chat', max_length=50)),
            ],
            options={
                'db_table': 'token_usage',
                'ordering': ['-timestamp'],
            },
        ),
    ]
