# Generated by Django 6.0.2 on 2026-02-07 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyusagesummary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_usage', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='hourlyperformancesummary',
            index=models.Index(fields=['endpoint', 'hour'], name='hourly_perf_endpoin_d2afff_idx'),
        ),
        migrations.AddField(
            model_name='requestmetrics',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_metrics', to='chat.chatsession'),
        ),
        migrations.AddField(
            model_name='requestmetrics',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_metrics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='systemhealth',
            index=models.Index(fields=['service_name', 'timestamp'], name='system_heal_service_61c959_idx'),
        ),
        migrations.AddField(
            model_name='tokenusage',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_usage', to='chat.chatsession'),
        ),
        migrations.AddField(
            model_name='tokenusage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_usage', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='dailyusagesummary',
            unique_together={('user', 'date')},
        ),
        migrations.AddIndex(
            model_name='requestmetrics',
            index=models.Index(fields=['endpoint', 'timestamp'], name='request_met_endpoin_79226c_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenusage',
            index=models.Index(fields=['user', 'timestamp'], name='token_usage_user_id_dd3fa1_idx'),
        ),
    ]
