# Generated by Django 6.0.2 on 2026-02-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyusagesummary',
            name='flashcards_reviewed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailyusagesummary',
            name='mock_tests_taken',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
