[project]
name = "code"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=6.0",
    "djangorestframework>=3.16.1",
    "faiss-cpu>=1.12.0",
    "fastapi>=0.116.1",
    "git-filter-repo>=2.47.0",
    "langchain>=0.3.0",
    "langchain-community>=0.3.0",
    "langchain-core>=0.3.0",
    "langchain-google-genai>=2.0.8",
    "langchain-groq>=0.3.8",
    "langchain-huggingface>=0.3.1",
    "langchain-openai>=0.3.30",
    "langchain-text-splitters>=0.3.0",
    "scipy>=1.11.0",
    "pinecone>=8.0.0",
    "psycopg2-binary>=2.9.11",
    "pypdf2>=3.0.1",
    "python-docx>=1.2.0",
    "python-dotenv>=1.1.1",
    "python-multipart>=0.0.20",
    "rank-bm25>=0.2.2",
    "sentence-transformers>=5.1.0",
    "soundfile>=0.13.1",
    "uvicorn[standard]>=0.35.0",
    "websockets>=15.0.1",
    "psycopg[binary]>=3.3.2",
    "dotenv>=0.9.9",
    "langgraph>=1.0.8",
]
