# Generated by Django 6.0.2 on 2026-04-18 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_google_id_user_profile_picture_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_access_token',
            field=models.TextField(blank=True, help_text='Google OAuth Access Token', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='google_refresh_token',
            field=models.TextField(blank=True, help_text='Google OAuth Refresh Token', null=True),
        ),
    ]
