# Generated by Django 6.0.2 on 2026-04-14 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='submission',
            name='exactly_one_assessment',
        ),
    ]
