# Generated by Django 6.0.2 on 2026-04-18 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_submission_exactly_one_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='quiz',
            field=models.ForeignKey(blank=True, help_text='Optional quiz attached to this assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='core.quiz'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='study_material',
            field=models.ForeignKey(blank=True, help_text='Source material used to generate this assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='core.studymaterial'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='total_marks',
            field=models.FloatField(default=100.0),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='course_id',
            field=models.CharField(blank=True, help_text='Google Classroom Course ID', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
