# Generated by Django 6.0.2 on 2026-05-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_assignment_quiz_assignment_study_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='grading_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='study_materials/'),
        ),
    ]
