# Generated by Django 6.0.2 on 2026-06-23 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_message_metadata'),
        ('core', '0004_submission_grading_details_alter_studymaterial_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='origin_session',
            field=models.ForeignKey(blank=True, help_text='The chat session where this file was uploaded', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_materials', to='chat.chatsession'),
        ),
    ]
