# Generated by Django 6.0 on 2026-02-01 15:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_chatsession_message_sessionmemory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyPerformanceSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hour', models.DateTimeField(db_index=True)),
                ('endpoint', models.CharField(blank=True, max_length=200, null=True)),
                ('total_requests', models.PositiveIntegerField(default=0)),
                ('avg_response_time_ms', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('p50_response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('p95_response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('p99_response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('error_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
            ],
            options={
                'db_table': 'hourly_performance_summary',
                'ordering': ['-hour'],
                'indexes': [models.Index(fields=['endpoint', 'hour'], name='hourly_perf_endpoin_d2afff_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemHealth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('service_name', models.CharField(choices=[('api', 'API Server'), ('database', 'Database'), ('llm_groq', 'Groq LLM'), ('llm_gemini', 'Gemini LLM'), ('pinecone', 'Pinecone Vector DB')], db_index=True, max_length=100)),
                ('is_healthy', models.BooleanField(default=True)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'system_health',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['service_name', 'timestamp'], name='system_heal_service_61c959_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyUsageSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('total_requests', models.PositiveIntegerField(default=0)),
                ('total_input_tokens', models.PositiveIntegerField(default=0)),
                ('total_output_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('total_cost_usd', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('model_breakdown', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'daily_usage_summary',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='RequestMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('endpoint', models.CharField(db_index=True, max_length=200)),
                ('method', models.CharField(max_length=10)),
                ('response_time_ms', models.PositiveIntegerField()),
                ('llm_latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('db_latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('status_code', models.PositiveIntegerField()),
                ('is_error', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('time_to_first_token_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_metrics', to='database.chatsession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'request_metrics',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['endpoint', 'timestamp'], name='request_met_endpoin_79226c_idx')],
            },
        ),
        migrations.CreateModel(
            name='TokenUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('model_name', models.CharField(max_length=100)),
                ('provider', models.CharField(max_length=50)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('request_type', models.CharField(choices=[('chat', 'Chat'), ('embedding', 'Embedding'), ('rag_query', 'RAG Query')], default='chat', max_length=50)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_usage', to='database.chatsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'token_usage',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='token_usage_user_id_dd3fa1_idx')],
            },
        ),
    ]
