# Generated by Django 6.0.2 on 2026-02-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='context_id',
            field=models.UUIDField(blank=True, help_text='ID of the related object (e.g., StudyMaterial ID, Assignment ID)', null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='context_type',
            field=models.CharField(choices=[('general', 'General'), ('study_material', 'Study Material'), ('assignment', 'Class Assignment'), ('flashcard', 'Flashcard Review')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='sources',
            field=models.JSONField(blank=True, default=list, help_text='List of source citations for RAG responses'),
        ),
    ]
