# Generated by Django 6.0.2 on 2026-02-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatsession_context_id_chatsession_context_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='context_type',
            field=models.CharField(choices=[('general', 'General'), ('study_material', 'Study Material'), ('assignment', 'Class Assignment'), ('flashcard', 'Flashcard Review'), ('mock_test', 'Mock Test')], default='general', max_length=20),
        ),
    ]
