# Generated by Django 6.0.2 on 2026-02-28 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_chatsession_context_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='context_id',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='context_type',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sources',
        ),
    ]
