import React from "react";
import Sidebar from "../TeacherDashboard/components/Sidebar";
import Header from "../TeacherDashboard/components/Header";
import AssignmentsList from "./components/AssignmentsList";
import { LuClipboardList } from "react-icons/lu";

const TeacherAssignments: React.FC = () => {
  return (
    <div className="flex flex-col lg:flex-row min-h-screen bg-gray-50 dark:bg-slate-950 font-inter text-gray-800 dark:text-slate-100">
      <Sidebar />
      <main className="flex-1 flex flex-col min-w-0 overflow-hidden">
        <Header />
        <div className="flex-1 overflow-y-auto p-6 space-y-6">
          {/* Page Title */}
          <div className="flex items-center justify-between">
            <div>
              <h1 className="text-2xl font-bold text-gray-900 dark:text-white flex items-center gap-3">
                <span className="w-9 h-9 rounded-xl bg-indigo-100 dark:bg-indigo-900/30 flex items-center justify-center text-indigo-600 dark:text-indigo-400">
                  <LuClipboardList className="w-5 h-5" />
                </span>
                Assignments
              </h1>
              <p className="text-sm text-gray-500 dark:text-slate-400 mt-1 ml-12">
                All assignments generated by the AI agent for your classes.
              </p>
            </div>
          </div>

          <AssignmentsList />
        </div>
      </main>
    </div>
  );
};

export default TeacherAssignments;
